# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d80deed87815e0e020e1d4af074d6e4269146e9ee94591543a24f6f3c3f9973a5ee2f588372d300196c8702e546f8742d9ec852235c36c6287f89521468def14
  google_client_id: 877496230852-5jm7s9thh78dhh4dd9mcngvis6v0fuso.apps.googleusercontent.com
  google_client_secret: KVrq2WwyvFc-vQIM7pMQxaBB
  facebook_client_id: 1548875422076959
  facebook_client_secret: 47473acdb5da0e6257c577abb626d250

test:
  secret_key_base: 48db8e1b77d7467053abb63f236dde2348c2ddd59c468f30ba70f09aab6afa6e4d085431d305e8677900523f53dc5a0cced8f67c740e1de66bbe888be1a16be2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
